### ISSUE TITLE
Search by id?

### ISSUE THREAD

**Issue by simonff** [jjrom/resto#233]
I'm trying to find out download URLs on PEPS by product id. This only seems to work for S1: https://peps.cnes.fr/resto/api/collections/S1/search.json?identifier=S1A_IW_GRDH_1SDH_20160723T101221_20160723T101250_012274_013151_16AE gives me back the correct result, but doing the same for S2 or S3 returns nothing: https://peps.cnes.fr/resto/api/collections/S2/search.json?maxRecords=1&identifier=S2A_MSIL1C_20160222T065901_N0204_R063_T39PUS_20180205T191150 or https://peps.cnes.fr/resto/api/collections/S3/search.json?maxRecords=2&identifier=S3A_OL_1_EFR____20180403T155615_20180403T155915_20180403T175343_0179_029_325_2340_SVL_O_NR_002

(I realize resto authors have no direct control of PEPS, but I thought I'll ask here first to make sure I'm sending correct queries.)

**Comment by jjrom** [comment]
Hi Simon, I developed the very first release of PEPS almost three years ago but since then i don't have any control of the source code so i cannot dig into the code right know.

However the request structure is good and it should work (note that maxRecords=1 is unneeded).

It looks like your identifiers are not correct or that the product is not present in the database. Where did you get it ?  

For instance here is are two woking requests (Sentinel-2, Sentinel-3) with existing identifies that exactly follow your request form:

https://peps.cnes.fr/resto/api/collections/S2/search.json?identifier=S2A_OPER_PRD_MSIL1C_PDMC_20161206T135131_R031_V20161206T013712_20161206T013712

https://peps.cnes.fr/resto/api/collections/S3/search.json?identifier=S3A_SR_2_LAN____20180405T042956_20180405T043955_20180405T053813_0599_029_347______SVL_O_NR_003

**Comment by tdrivas** [comment]
Hello,

Is there any way to get from peps api only the online products? There is a property called storage with mode either tape or disk (this is the property I want), but it does not work when I set it as a property in the search query. 

Thanks in advance!

**Comment by jjrom** [comment]
Hi,

I'm no more in charge of the PEPS development and the "storage" property was added after i left so i cannot tell how it was implemented. 
You should post your question to the PEPS team here https://peps.cnes.fr/rocket/#/contact

Regards

**Comment by tdrivas** [comment]
Thank you very much for your direct response! Take care!
