### ISSUE TITLE
Documentation insertFeature body is not inputFeature schema

### ISSUE THREAD

**Issue by qgau** [jjrom/resto#432]
In self-hosted API documentation for insertFeature, the request body schema is `any` instead of `InputFeature`.

**Comment by jjrom** [comment]
The HTML documentation is automatically generated from the PHP swagger annotations in the code, specifically these lines : https://github.com/jjrom/resto/blob/master/app/resto/core/api/CollectionsAPI.php#L555-L563

The subsequent HTML indicates "any" for the type which can be confusing but the description is clear : "Either a GeoJSON Feature or a GeoJSON FeatureCollection".

Since the HTML cannot be modified "by hand" (automatically generated). I close this comment
